//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AussieDiversEntities : DbContext
    {
        public AussieDiversEntities()
            : base("name=AussieDiversEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beach> Beaches { get; set; }
        public virtual DbSet<Boat> Boats { get; set; }
        public virtual DbSet<BookedPackage> BookedPackages { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingDetail> BookingDetails { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<CommunicationHistory> CommunicationHistories { get; set; }
        public virtual DbSet<DiveHistory> DiveHistories { get; set; }
        public virtual DbSet<DiveSite> DiveSites { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentHistory> EquipmentHistories { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonCertification> PersonCertifications { get; set; }
        public virtual DbSet<PersonHotel> PersonHotels { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
    }
}
