//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingDetail()
        {
            this.PersonHotels = new HashSet<PersonHotel>();
            this.Rentals = new HashSet<Rental>();
        }
    
        public int BookingDetailsID { get; set; }
        public short BookedPackageID { get; set; }
        public int PersonID { get; set; }
        public short BookedEmployeeID { get; set; }
        public short BoatID { get; set; }
        public System.DateTime BD_DiveDate { get; set; }
        public string BD_Status { get; set; }
        public string BD_CustomerHotel { get; set; }
        public string BD_PickupLocation { get; set; }
    
        public virtual Boat Boat { get; set; }
        public virtual BookedPackage BookedPackage { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonHotel> PersonHotels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
        public virtual Person Person { get; set; }
    }
}
