//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiveHistory
    {
        public short DiveHistoryID { get; set; }
        public short DiveSiteID { get; set; }
        public int PersonID { get; set; }
    
        public virtual DiveSite DiveSite { get; set; }
        public virtual Person Person { get; set; }
    }
}
