//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public short EmergencyContactID { get; set; }
        public int PersonID { get; set; }
        public string EC_FirstName { get; set; }
        public string EC_LastName { get; set; }
        public string EC_Country { get; set; }
        public string EC_PhoneNumber { get; set; }
        public string EC_Relationship { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
