//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentHistory
    {
        public short EquipmentHistoryID { get; set; }
        public short EquipmentID { get; set; }
        public decimal EH_RetailCost { get; set; }
        public decimal EH_DatePurchased { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
