//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.PersonHotels = new HashSet<PersonHotel>();
        }
    
        public short HotelID { get; set; }
        public short BeachID { get; set; }
        public string HotelName { get; set; }
        public string HotelStreetAddress { get; set; }
        public string HotelCity { get; set; }
        public string HotelStateProvinceTerritory { get; set; }
        public string HotelCountry { get; set; }
        public string HotelPostalCode { get; set; }
        public string HotelPhoneNumber { get; set; }
        public string HotelDirections { get; set; }
    
        public virtual Beach Beach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonHotel> PersonHotels { get; set; }
    }
}
