//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public short PaymentID { get; set; }
        public short BookingID { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal PaymentBalance { get; set; }
        public short MethodID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
