//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCertification
    {
        public short PersonCertificationID { get; set; }
        public int PersonID { get; set; }
        public short CertificationID { get; set; }
        public System.DateTime PC_Date { get; set; }
        public string PC_PADI_ID { get; set; }
    
        public virtual Certification Certification { get; set; }
        public virtual Person Person { get; set; }
    }
}
