//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.CommunicationHistories = new HashSet<CommunicationHistory>();
            this.DiveHistories = new HashSet<DiveHistory>();
            this.EmergencyContacts = new HashSet<EmergencyContact>();
            this.PersonCertifications = new HashSet<PersonCertification>();
        }
    
        [Display(Name="ID")]
        public int PersonID { get; set; }
        [Display(Name="First Name")]
        public string PersonFirstName { get; set; }
        [Display(Name = "Last Name")]
        public string PersonLastName { get; set; }
        [Display(Name = "Email")]
        public string PersonEmail { get; set; }
        [Display(Name = "Date of Birth")]
        public System.DateTime PersonDOB { get; set; }
        public Nullable<System.DateTime> PersonLastDiveDate { get; set; }
        public Nullable<short> PersonNumberOfDives { get; set; }
        public string PersonStreetAddress1 { get; set; }
        public string PersonStreetAddress2 { get; set; }
        public string PersonCity { get; set; }
        public string PersonStateProvinceTerritory { get; set; }
        public string PersonCountry { get; set; }
        public string PersonPostalCode { get; set; }
        public string PersonPhone { get; set; }
        public string PersonVegetarian { get; set; }
        public string PersonAllergies { get; set; }
        public byte[] PersonPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunicationHistory> CommunicationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiveHistory> DiveHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCertification> PersonCertifications { get; set; }
    }
}
