//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public short RentalID { get; set; }
        public short EquipmentID { get; set; }
        public int BookingDetailsID { get; set; }
        public string RentalStatus { get; set; }
    
        public virtual BookingDetail BookingDetail { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
