//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public short ScheduleID { get; set; }
        public short BoatID { get; set; }
        public short DiveSiteID { get; set; }
        public string ScheduleDayOfWeek { get; set; }
    
        public virtual Boat Boat { get; set; }
        public virtual DiveSite DiveSite { get; set; }
    }
}
